name: Build EAGLE Firmware

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Cache ARM toolchain
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/arm-toolchain
        key: ${{ runner.os }}-arm-gcc-9.2.1
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          gcc-arm-none-eabi \
          cmake \
          python3 \
          python3-pip \
          dfu-util \
          hackrf
          
    - name: Verify ARM GCC
      run: arm-none-eabi-gcc --version
      
    - name: Create build directory
      run: mkdir -p build
      
    - name: Configure CMake
      working-directory: build
      run: cmake ..
      
    - name: Build firmware
      working-directory: build
      run: make -j$(nproc)
      
    - name: List build artifacts
      working-directory: build/firmware
      run: ls -lah *.bin
      
    - name: Upload firmware artifacts
      uses: actions/upload-artifact@v3
      with:
        name: eagle-firmware-build
        path: |
          build/firmware/*.bin
          build/hackrf/firmware/*.dfu
          
    - name: Create release package
      if: github.event_name == 'release'
      run: |
        mkdir -p release
        cp build/firmware/*.bin release/
        cp README_EAGLE.md release/README.md
        cd release && zip -r eagle-firmware-${{ github.ref_name }}.zip .
        
    - name: Upload to release
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./release/eagle-firmware-${{ github.ref_name }}.zip
        asset_name: eagle-firmware-${{ github.ref_name }}.zip
        asset_content_type: application/zip
